sudo: false
language: node_js
node_js:
  - '4.2'
branches:
  only:
    - source

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libcairo2-dev
      - libjpeg8-dev
      - libgif-dev
      - libpango1.0-dev
      - graphicsmagick
      - libjpeg-turbo-progs
      - inkscape

env:
  global:
    - CXX='g++-4.8'
    - CC='gcc-4.8'
    - secure: lVmR1xSQrL8NZwfGQgbR9SiwXjmdbCOxZIMmLRE2OZJ01dJ1BjI1g3tfPeV5WvOjvwo7AcoMxQE6C7wuxbnqSPvLLuyvud6irCnFnW3ra9X2iYcwFR/n40b4XBdm1vF35klSSe9KVq3n6oKvZR7dJaEykmKNreUOoqN1zxrY16g=

before_install:
  - rvm install 2.1.1
before_script:
  - git config --global user.name 'Travis-CI'
  - git config --global user.email 'travis@yeoman.io'
  - gem install bundler
  - bundle install

# Silent the script output, we don't want any key made public in the Travis log
script: npm run-script deploy

# Compiling a lot of our dependencies takes forever. We're caching them
cache:
  bundler: true
  directories:
    - node_modules
