name: Update generator api
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - run: npm install -g jsdoc-to-markdown
      - uses: actions/checkout@v2
        with:
          path: page
      - uses: actions/checkout@v2
        with:
          repository: yeoman/generator
          path: generator
      - uses: actions/checkout@v2
        with:
          repository: yeoman/yeoman-test
          path: test
      - uses: actions/checkout@v2
        with:
          repository: yeoman/environment
          path: environment
      - name: Update jsdoc
        run: |
          cd page
          mkdir -p app/api/generator
          mkdir -p app/api/environment
          mkdir -p app/api/test
          jsdoc2md ../generator/lib/*.js > app/api/generator/api.md
          jsdoc2md ../generator/lib/actions/*.js > app/api/generator/actions.md
          jsdoc2md ../generator/lib/util/*.js > app/api/generator/util.md
          jsdoc2md ../test/lib/*.js > app/api/test/api.md
          jsdoc2md ../environment/lib/*.js > app/api/environment/api.md
          jsdoc2md ../environment/lib/util/*.js > app/api/environment/util.md
          git add .
          git config --local user.email "mshima@users.noreply.github.com"
          git config --local user.name "Marcelo Shima"
          git commit -a -m "Update generator api"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update generator api
          committer: Marcelo Shima <mshima@users.noreply.github.com>
          author: Marcelo Shima <mshima@users.noreply.github.com>
          title: 'Update generator api'
          body: |
            Update generator api with last master version
          labels: automated pr
          branch: api-generator
          path: page
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"

